// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/course_category.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Category struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde79cb73866aac8, []int{0}
}

func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (m *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(m, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Category) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

//toda vez q receber um resultado, vc pode receber várias categorias.
type CategoryResponse struct {
	Category             *Category `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CategoryResponse) Reset()         { *m = CategoryResponse{} }
func (m *CategoryResponse) String() string { return proto.CompactTextString(m) }
func (*CategoryResponse) ProtoMessage()    {}
func (*CategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde79cb73866aac8, []int{1}
}

func (m *CategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoryResponse.Unmarshal(m, b)
}
func (m *CategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoryResponse.Marshal(b, m, deterministic)
}
func (m *CategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoryResponse.Merge(m, src)
}
func (m *CategoryResponse) XXX_Size() int {
	return xxx_messageInfo_CategoryResponse.Size(m)
}
func (m *CategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CategoryResponse proto.InternalMessageInfo

func (m *CategoryResponse) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

type CreateCategoryRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCategoryRequest) Reset()         { *m = CreateCategoryRequest{} }
func (m *CreateCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCategoryRequest) ProtoMessage()    {}
func (*CreateCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde79cb73866aac8, []int{2}
}

func (m *CreateCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCategoryRequest.Unmarshal(m, b)
}
func (m *CreateCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCategoryRequest.Marshal(b, m, deterministic)
}
func (m *CreateCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCategoryRequest.Merge(m, src)
}
func (m *CreateCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCategoryRequest.Size(m)
}
func (m *CreateCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCategoryRequest proto.InternalMessageInfo

func (m *CreateCategoryRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCategoryRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*Category)(nil), "pb.Category")
	proto.RegisterType((*CategoryResponse)(nil), "pb.CategoryResponse")
	proto.RegisterType((*CreateCategoryRequest)(nil), "pb.CreateCategoryRequest")
}

func init() {
	proto.RegisterFile("proto/course_category.proto", fileDescriptor_fde79cb73866aac8)
}

var fileDescriptor_fde79cb73866aac8 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x31, 0x4b, 0xc5, 0x30,
	0x14, 0x85, 0x6d, 0x14, 0x79, 0xde, 0xea, 0x53, 0x2e, 0x0a, 0x55, 0x97, 0x92, 0xa9, 0x53, 0x0b,
	0x75, 0x75, 0xb2, 0xb3, 0x20, 0x15, 0x1c, 0x5c, 0x24, 0x49, 0x2f, 0x12, 0xd0, 0x24, 0x26, 0xa9,
	0xe0, 0xbf, 0x17, 0x42, 0x5b, 0x2d, 0xfa, 0xb6, 0x70, 0x4e, 0xf8, 0xce, 0x97, 0xc0, 0xb5, 0xf3,
	0x36, 0xda, 0x46, 0xd9, 0xd1, 0x07, 0x7a, 0x51, 0x22, 0xd2, 0xab, 0xf5, 0x5f, 0x75, 0x4a, 0x91,
	0x39, 0xc9, 0x1f, 0x60, 0xd3, 0x4d, 0x29, 0x6e, 0x81, 0xe9, 0xa1, 0xc8, 0xca, 0xac, 0x3a, 0xea,
	0x99, 0x1e, 0x10, 0xe1, 0xc0, 0x88, 0x77, 0x2a, 0x58, 0x4a, 0xd2, 0x19, 0x4b, 0xc8, 0x07, 0x0a,
	0xca, 0x6b, 0x17, 0xb5, 0x35, 0xc5, 0x7e, 0xaa, 0x7e, 0x47, 0xfc, 0x16, 0xce, 0x66, 0x62, 0x4f,
	0xc1, 0x59, 0x13, 0x08, 0x2b, 0xd8, 0xcc, 0xdb, 0x89, 0x9f, 0xb7, 0xc7, 0xb5, 0x93, 0xf5, 0x72,
	0x6f, 0x69, 0xf9, 0x3d, 0x5c, 0x74, 0x9e, 0x44, 0xa4, 0x1f, 0xc6, 0xc7, 0x48, 0x21, 0x2e, 0x32,
	0xd9, 0x6e, 0x19, 0xf6, 0x47, 0xa6, 0x7d, 0x82, 0xd3, 0x19, 0xf4, 0x48, 0xfe, 0x53, 0x2b, 0xc2,
	0x0e, 0xb6, 0xeb, 0x05, 0xbc, 0x4c, 0x2e, 0xff, 0xad, 0x5e, 0x9d, 0xaf, 0x34, 0xa7, 0xe7, 0xf0,
	0xbd, 0xbb, 0x93, 0xe7, 0x5c, 0x9b, 0x48, 0xde, 0x88, 0xb7, 0xc6, 0x49, 0x79, 0x98, 0x3e, 0xf4,
	0xe6, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xde, 0x42, 0xa1, 0xae, 0x6f, 0x01, 0x00, 0x00,
}
